### ISSUE TITLE
require modules

### ISSUE THREAD

**Issue by Keks1993** [ctxis/beemka#2]
The "vscode_sources" module has a variable-dependency string for working with the file system (require ('fs')).
When this module is injected, the execution of the payload code stops just when accessing this line (require ('fs')) and then the code does not work. Tell me, what needs to be done to make payload code work?

**Comment by sadreck** [comment]
Into which application are you trying to inject that module? Because that module was specifically written for "Visual Studio Code"

**Comment by Keks1993** [comment]
I am trying to understand the General concept and write a module for WhatsApp to save messages to a file.

**Comment by Keks1993** [comment]
So you tell me whether there is such a possibility?

**Comment by sadreck** [comment]
Hi,

Apologies for the delay!

You cannot use the existing vscode module for WhatsApp as it currently is.

The way I would approach this, would be to enable Developer Tools in whatsapp, experiment in the console, and after you have a snippet that works, put it into a new module (c/p vscode and rename it).

Hopefully I'll get free time soon to write up some documentation on writing module from scratch, but until then unfortunately it will have to be trial and error.

Pavel
