### ISSUE TITLE
Module: Slack Session Injection Failed

### ISSUE THREAD

**Issue by TheBull963** [ctxis/beemka#3]
Hello, I am testing out the Slack_session module and am receiving an exception fault when doing the injection. Here is the error I am getting: 

Traceback (most recent call last):
  File "beemka.py", line 122, in <module>
    if not injector.inject(asar_file, asar_working_path, module, module_data, output_file, worker):
  File "\beemka\classes\injector.py", line 17, in inject
    if worker_class.run(worker_data) is False:
  File "\beemka\modules\slack_session\worker.py", line 27, in run
    raise Exception("Could not inject payload into chrome-extension.js - probably an update broke this module")
Exception: Could not inject payload into chrome-extension.js - probably an update broke this module

Have you run into this issue before?

**Comment by sadreck** [comment]
Hello - I've just made a change in the module to fix this - https://github.com/ctxis/beemka/commit/754ab3178b33b107f626b1e23d1dbba1dc455202

Try pulling the latest code and giving it another go - I'll close this for now and re-open if the issue persists.
